filter:
  excluded_paths: [tests/*, vendor/*, optimizers/*]

checks:
  php:
    code_rating: true

before_commands:
  - "composer install --prefer-source"

tools:
  # Analyzes the size and structure of a PHP project.
  php_pdepend:
    enabled: true
    command: pdepend
    excluded_dirs:
      - vendor

  # Runs Scrutinizer's PHP Analyzer Tool
  php_analyzer:
    enabled: true
    filter:
      excluded_paths:
        - 'vendor/*'

  # Security Advisory Checker
  sensiolabs_security_checker: true
