language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: 7.0  

install: 
  - composer install --no-interaction --prefer-source
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --report=summary --standard=PSR2 --ignore=/vendor/* --extensions=php .
